### ISSUE TITLE
Enumerating with days of week range

### ISSUE THREAD

**Issue by kipcole9** [kipcole9/tempo#15]
```elixir
iex> Enum.to_list ~o"2018Y1W{1..5}K"
** (MatchError) no match of right hand side value: {:error, "{1, #Function<0.68771310/2 in Tempo.Enumeration.continuation/3>} is not valid. The valid values are 1..7"}
    (tempo 0.2.0-dev) lib/protocol/enumeration/tempo.ex:60: Enumerable.Tempo.make_enum/1
    (tempo 0.2.0-dev) lib/protocol/enumeration/tempo.ex:39: Enumerable.Tempo.reduce/3
    (elixir 1.15.4) lib/enum.ex:4387: Enum.reverse/1
    (elixir 1.15.4) lib/enum.ex:3702: Enum.to_list/1
    iex:21: (file)
```

**Comment by kipcole9** [comment]
Fixed.
```elixir
iex> Enum.to_list ~o"2018Y1W{1..5}K"
[~o"2018Y1W1K", ~o"2018Y1W2K", ~o"2018Y1W3K", ~o"2018Y1W4K", ~o"2018Y1W5K"]
```
